In [1]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
matrix_1 = np.array([[2,3], [6,7]])
matrix_1

array([[2, 3],
       [6, 7]])

In [4]:
matrix_1.shape

(2, 2)

Matrix with random values

In [5]:
random_matrix = np.random.rand(3,3)
random_matrix

array([[0.38963096, 0.2473414 , 0.18768359],
       [0.07510272, 0.29251568, 0.48105928],
       [0.86962218, 0.79393939, 0.22857925]])

In [6]:
random_integer_matrix = np.random.randint(100, size=(4,5))
print(random_integer_matrix)

[[68 32 43 84 61]
 [21 16  7 48 66]
 [61  3 66 29 57]
 [54 80 41 37 20]]


All ones

In [7]:
matrix_2 = np.ones((2,3))
print(matrix_2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [8]:
matrix_2 = np.ones((2,3), dtype = int)
matrix_2

array([[1, 1, 1],
       [1, 1, 1]])

Null Matrix or zero matrix

In [9]:
null_matrix = np.zeros((4,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity matrix

In [11]:
identity_matrix = np.eye(3,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Transpose

In [12]:
a = np.random.randint(100, size=(4,5))
print(a)

[[86 51 57 13 34]
 [90 15 30 58 36]
 [51 80 18 92 58]
 [99 29 11  4 64]]


In [13]:
transpose = np.transpose(a)
print(transpose)

[[86 90 51 99]
 [51 15 80 29]
 [57 30 18 11]
 [13 58 92  4]
 [34 36 58 64]]


Matrix Addition - A + B

Matrix difference = A - B

Matrix multiplication = np.multiply (mat_1, mat_2) - mat_1 or mat_2 can be scalar too

In [17]:
A = np.array([[2,3],[4,5]])
B = np.array([[6,7],[8,9]])

sum = np.add(A, B)
difference = A - B
product = np.multiply(A,B)
scalar_product = np.multiply(A, 2)
dot_product = np.dot(A,B)
print(sum)
print(difference)
print(product)
print(scalar_product)
print(dot_product)

[[ 8 10]
 [12 14]]
[[-4 -4]
 [-4 -4]]
[[12 21]
 [32 45]]
[[ 4  6]
 [ 8 10]]
[[36 41]
 [64 73]]
