 # Load in Numpy

In [5]:
import numpy as np

# The Basics

In [7]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [9]:
b = np.array([[9.0, 8.0, 7.0], [6.0, 5.0, 4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [11]:
#get dimension
a.ndim

1

In [13]:
#get shape or row vs column
b.shape

(2, 3)

In [15]:
#get type of elements
a.dtype

dtype('int32')

In [17]:
#get size in bytes
a.itemsize

4

In [19]:
#to get length of array
a.size

3

# Accessing/Changing specific elements, rows, columns, etc

In [21]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [24]:
a.shape #rows*column


(2, 7)

In [26]:
# accessing [r,c]
a[1,5]

13

In [29]:
#accessing [r,c] but from end
a[1, -3] # first row, last second column

12

In [31]:
#to get whole row 
a[0, :] # : - this means take all

array([1, 2, 3, 4, 5, 6, 7])

In [33]:
#[startindex:endindex:stepsize]
a[0, 1:6:2]

array([2, 4, 6])

In [35]:
#to change any element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


# Initializing Different type of arrays

In [55]:
#all zeros matrix
np.zeros(5)
# np.zeros((2,3)) - to make a 2 by 3 matrix of all zeros

array([0., 0., 0., 0., 0.])

In [56]:
#all one matrix
#d= np.ones(4) #by default datatype = float64
#print(d.dtype)
d = np.ones(4, dtype = 'int32')

In [57]:
#any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [58]:
#random decimal numbers
np.random.rand(4,2)

array([[0.04577202, 0.1668927 ],
       [0.44370405, 0.52416707],
       [0.16566922, 0.62920074],
       [0.24941928, 0.49480252]])

In [64]:
#random integer value in a range
np.random.randint(9, size = (3,3)) # number generated will be less than 9 always

array([[8, 6, 7],
       [4, 1, 7],
       [4, 5, 5]])

In [69]:
np.random.randint(5, 10, size = (2,2)) #number generated will be in range now 5 to 10

array([[6, 5],
       [6, 9]])

In [71]:
#to create identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis = 0) #when kept axis 0, it will make more rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


# don't directly copy arrays

In [75]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)           #it changed a too so don't do it like this

[100   2   3]


In [77]:
#instead this is right way
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)

[1 2 3]
[100   2   3]


# Mathematics

In [78]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [80]:
a + 2 #adds number to each element

array([3, 4, 5, 6])

In [82]:
a - 2 

array([-1,  0,  1,  2])

In [84]:
a*2

array([2, 4, 6, 8])

In [86]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [88]:
b = np.array([1,0,1,0]) #addition of two matrix
a + b


array([2, 2, 4, 4])

In [91]:
a ** 2 # this is power not multiplication

array([ 1,  4,  9, 16], dtype=int32)

In [93]:
np.sin(a) #take sine value of each element

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [95]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

# Linear Algebra

In [104]:
#multiplication of two matrices
a = np.ones((2, 3))
b = np.full((3, 2), 2)
result = np.matmul(a, b)

print(result)

[[6. 6.]
 [6. 6.]]


In [106]:
# to find determinant
c = np.identity(3)
np.linalg.det(c)  #linear algebra module

1.0

# statistics

In [113]:
stats = np.array([[1,2,3], [4,1,6]])
stats

array([[1, 2, 3],
       [4, 1, 6]])

In [109]:
np.min(stats)

1

In [111]:
np.max(stats)

6

In [115]:
np.min(stats, axis = 0) # row wise min

array([1, 1, 3])

In [117]:
np.sum(stats)

17

In [119]:
np.sum(stats, axis = 1)

array([ 6, 11])

# Reorganizing arrays

In [124]:
before = np.array([[1,2,3,4], [5,6,7,8]])
print(before)

after = before.reshape((2,4)) 
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]]


In [126]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [128]:
#horizontally stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.hstack([v1,v2])

array([1, 2, 3, 4, 5, 6, 7, 8])

# Boolean masking

In [132]:
filedata = np.array([[1, 13, 21, 11, 196, 75, 4, 3, 34, 6, 7, 8, 0, 1, 2, 3, 4, 5],
            [3, 42, 12, 33, 766, 75, 4, 55, 6, 4, 3, 4, 5, 6, 7, 0, 11, 12],
            [1, 22, 33, 11, 999, 11, 2, 1, 78, 0, 1, 2, 9, 8, 7, 1, 76, 88]])

In [134]:
filedata[filedata > 50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

In [136]:
# index with list in numpy
a = np.array([1,2,3,4,2,13,4,6,7])
a[[1,2,6]]

array([2, 3, 4])

In [139]:
np.any(filedata > 50, axis = 0) #this checks if there is any element which
#satisfies the condition and then returns value for each element

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])